#!/bin/bash
# This file should be generated by our ServicePanel, and provisioned with the SSH-keys that the customer has on his Hypernode

set -e

user="app"
homedir=$(getent passwd $user | cut -d ':' -f6)
sudo -u $user mkdir -p "$homedir/.ssh"
sudo -u $user touch "$homedir/.ssh/authorized_keys"
chmod 700 "$homedir/.ssh"
chmod 600 "$homedir/.ssh/authorized_keys"

if ssh-add -L >/dev/null 2>/dev/null; then
    ssh-add -L >> $homedir/.ssh/authorized_keys;
fi

cat << EOF >> $homedir/.ssh/authorized_keys
EOF

rm -rf /etc/cron.d/hypernode-fpm-monitor

# Update magerun to the latest version
/usr/local/bin/n98-magerun -q self-update || true
